### ISSUE TITLE
Compilation broken after latest commit

### ISSUE THREAD

**Issue by ghost** [unicredit/nimblas#1]
Hello!
This used to work but now fails:
`nim c -d:atlas -r test_mat.nim`
Error:
`could not load: libcblas.so.(|3|2|1|0)`
However editing nimblas/private/common.nim line 20, fixes the problem

Thank you.

**Comment by andreaferretti** [comment]
Uhm... I had edited this because other users were not able to locate `libcblas.so` (without trailing numbers).

Can you tell me what OS you are using and what is the name of `libcblas` on your system (possibly more than one due to symlinks)?

**Comment by andreaferretti** [comment]
For instance on my system `locate libcblas` prints

```
/usr/lib/libcblas.a
/usr/lib/libcblas.so
/usr/lib/libcblas.so.3
/usr/lib/atlas-base/libcblas.a
/usr/lib/atlas-base/libcblas.so
/usr/lib/atlas-base/libcblas.so.3
/usr/lib/atlas-base/libcblas.so.3.0
```

**Comment by ghost** [comment]
I am using Manjaro and I have packages blas and cblas installed. When I give `locate libcblas` I just get: 
`/usr/lib/libcblas.so`
