### ISSUE TITLE
Linking to blas.dll on windows

### ISSUE THREAD

**Issue by auxym** [unicredit/nimblas#8]
I might be missing something obvious here, but I can't get an executable using nimblas to load `blas.dll` on windows.

I have this simple nim code, ripped from the tests:

```nim
import nimblas/cblas

template first[A](x: openArray[A]): ptr A = addr(x[0])

var
  u = [1.0, 2.0, 3.0, 4.0]
  v = [2.0, 2.0, 2.0, 1.0]

let d = ddot(4, u.first, 1, v.first, 1)
echo d
```

I build with: `nim c -r blastest.nim`.

I have downloaded the [reference blas dll](http://icl.cs.utk.edu/lapack-for-windows/lapack/), renamed to `blas.dll` (the file is originally `libblas.dll`) and put it in the same folder as the compiled exe. Running the exe then gives me:

```
could not load: blas.dll
```

I have tried many permutations on the above : not renaming and using the `-d:blas=libblas` switch at compile time, using [openblas](https://www.openblas.net/) dll, both renamed to `blas.dll` and in its original `libopenblas.dll` with `-d:blas=openblas`

I've also triple-checked that all my various BLAS dll's, as well as my exe, are 64 bits. I'm building with nim 1.0.4 and mingw64 gcc: 

```
$gcc -v

Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-9.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --enable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 9.2.0 (Rev2, Built by MSYS2 project)
```

```
$nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
Hi @auxym , this is a little difficult to investigate for me since I don't have a Windows system and I have never programmed on Windows. Still, this library has been reported to work on Windows, so it must somehow work.

Where does Windows look for DLLs? Is it enough to put it in the executable folder or does it need to be installed somewhere? In [this issue](https://github.com/mratsim/Arraymancer/issues/242) for Arraymancer, I see that @systra72 is using Msys2 to install BLAS, while in [this other issue](https://github.com/mratsim/Arraymancer/issues/212) @pkscn333 reports it working via pacman.

I don't know if this is of any help

**Comment by auxym** [comment]
Putting DLL in the same folder as the executable is pretty standard on win32, and is the first place looked up according to this MS doc: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications

> If SafeDllSearchMode is enabled, the search order is as follows:
>
>    1. The directory from which the application loaded.
> ...

That said, I'll have a look at those issues (thanks!) and investigate. If I figure out the trick maybe we can update the readme or something.

**Comment by andreaferretti** [comment]
> If I figure out the trick maybe we can update the readme or something.

Sure, thank you!

**Comment by auxym** [comment]
Alright, I got it working by using openblas from msys2 (had no idea they were building and packaging it, what a great project!). I was already using the msys2 mingw64 compiler toolchain, so that worked out fine.

I suspect my original issue my caused by ABI incompability issues between MSVC-built dlls and my mingw/gcc executables.

In short, I'd suggest the following blurb in the readme:

```
## Linking BLAS Implementations

...

### Windows

On windows, it is recommended to use [MSYS2](https://www.msys2.org/) to install the mingw compiler toolchain and compatible OpenBLAS library. For 64-bit builds, this would be:

pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-openblas

You should then add `MSYS2_ROOT\mingw64\bin` to your PATH. Programs using nimblas can then
be compiled using the `-d:blas=libopenblas` switch. At runtime, `libopenblas,dll` should be loaded
from the mingw64 bin directory you added to your PATH, though it is suggested to distribute this 
dll file alongside your executable if your are publishing binary packages.
```

I'm not sure if it's because of the PATH entry I added, but I did not need to pass any additional `clibdir` switch, the dll was already on the default search path. On a related note, neo can also be built by adding `-d:lapack=libopenblas`.
```

**Comment by andreaferretti** [comment]
Thank you, I have added instructions for Windows. If you feel this is now ok, you can close the issue.

**Comment by auxym** [comment]
Works for me, thanks
